### PR TITLE
add readRender for oracle and mysql

### PR DESCRIPTION
**Pull request by mehulumistry**
This PR contains: #148 #149

### CODE REVIEW

**Review by robmwalsh — CHANGES_REQUESTED** [review]
@mehulumistry thanks for your work on this! Still a few things to work on to get those tests passing, mainly dialect specific. Let me know if you need a hand on anything. I'll change this to a draft for now.

**Comment by robmwalsh** [comment]
check out https://github.com/testcontainers/testcontainers-java/issues/2313 for what appears to be an easy fix!

**Comment by mehulumistry** [comment]
> @mehulumistry thanks for your work on this! Still a few things to work on to get those tests passing, mainly dialect specific. Let me know if you need a hand on anything. I'll change this to a draft for now.

The test is failing because of the exception: **Caused by: java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1 [info]   ORA-01882: timezone region not found.** 
This happens only on Oracle DB container testing, locally, I don't see any errors. And MySQL testing is successfully passed.

**Comment by mehulumistry** [comment]
> check out [testcontainers/testcontainers-java#2313](https://github.com/testcontainers/testcontainers-java/issues/2313) for what appears to be an easy fix!

I tried setting the timezone of testContainer by adding env `a.addEnv("TZ", "America/New_York")` and also tried property `"oracle.jdbc.timezoneAsRegion", "false"` but no luck. Need to look more into this.

**Comment by jczuchnowski** [comment]
Wow, this is awesome!

**Comment by jczuchnowski** [comment]
@mehulumistry you could split this PR into two separate: for Oracle and MySQL. At leas one of them could get in right away.

**Comment by mehulumistry** [comment]
> @mehulumistry you could split this PR into two separate: for Oracle and MySQL. At leas one of them could get in right away.

Done

**Pull request merged**
