### PR TITLE
update Dotty version and fix errors

### PR DESCRIPTION
**Pull request by jczuchnowski**

### CODE REVIEW

**Comment by jczuchnowski** [comment]
there's one error outstanding
```
[error] -- [E007] Type Mismatch Error: /home/giacomo/projects/zio/jczuchnowski.zio-sql/core/jvm/src/main/scala/Sql.scala:885:85 
[error] 885 |    def in[B1 >: B <: SelectionSet[_]](set: Read[B1]): Expr[F, A, Boolean] = Expr.In(self, set)
[error]     |                                                                                     ^^^^
[error]     |Found:    (Expr.this : Sql.this.Expr[F, A, B] & Sql.this.Expr[F, A, B])
[error]     |Required: Sql.this.Expr[F, A, Sql.this.SelectionSet[?]]
```

**Comment by jdegoes** [comment]
For now you could insert `asInstanceOf` in there to make it work.

**Comment by jdegoes** [comment]
This ready for merging?

**Comment by jczuchnowski** [comment]
No, not yet. Fixing this one problem uncovered couple more. Still working on it.

**Comment by jdegoes** [comment]
@jczuchnowski ???

**Comment by jczuchnowski** [comment]
I did some more work on ti. The `core` module seems to compile, but had to use couple of workarounds using `instanceOf`.
Unfortunately it uncovered a ton of other problems in descendant modules. In particular with how the DSL is used. So I'm leaving it as is for now as it take a lot of cycles to get through all of it.
I think this PR can be merged as is and we can pick up on this taks some other time.

Some examples:
```
[error] -- [E045] Cyclic Error: /home/giacomo/projects/zio/jczuchnowski.zio-sql/examples/src/main/scala/ShopSchema.scala:28:4 
[error] 28 |    val fkProductId :*: effective :*: price :*: _ = productPrices.columns
[error]    |    ^
[error]    |    Recursive value $5$ needs type
[error] Explanation
[error] ===========
[error] The definition of value $5$ is recursive and you need to specify its type.
```
or
```
[error] -- [E008] Not Found Error: /home/giacomo/projects/zio/jczuchnowski.zio-sql/examples/src/main/scala/ShopSchema.scala:9:72 
[error] 9 |    val users = (uuid("id") ++ localDate("dob") ++ string("first_name") ++ string("last_name")).table("users")
[error]   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |value ++ is not a member of ShopSchema.this.ColumnSet.Singleton[java.util.UUID]#Append[
[error]   |  ShopSchema.this.ColumnSet.Singleton[java.time.LocalDate]
[error]   |]#Append[ShopSchema.this.ColumnSet.Singleton[String]], but could be made available as an extension method.
[error]   |
[error]   |One of the following imports might make progress towards fixing the problem:
[error]   |
[error]   |  import ShopSchema.this.Expr.literal
[error]   |  import zio.sql.Examples.Expr.literal
```
or
```
[warn] -- Warning: /home/giacomo/projects/zio/jczuchnowski.zio-sql/jdbc/src/main/scala/zio/sql/jdbc.scala:305:51 
[warn] 305 |      ZStream.unwrap(ZIO.access[ReadExecutor](_.get.execute(read) { resultType =>
[warn]     |                                                   ^
[warn]     |Scala 2 macro cannot be used in Dotty, this call will crash at runtime. See https://dotty.epfl.ch/docs/reference/dropped-features/macros.html
```

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
Thank you! It's progress, anyway.

**Pull request merged**
