### PR TITLE
Complete typeTagOf implementation and fix 2.12 compilation issues

### PR DESCRIPTION
**Pull request by jczuchnowski**

### CODE REVIEW

**Review by jdegoes — COMMENTED** [review]
Looks good to me! We did this together so just go ahead and merge it when `mdoc`, etc. are passing.

**Comment by jczuchnowski** [comment]
Yeah, once I modified the `build.sbt` some more problems were uncovered. This time with the use of `deleteFrom`:
```
[error] /home/circleci/project/examples/src/main/scala/Example1.scala:39:17: inferred kinds of the type arguments (Example1.table.Repr[X],Example1.table.TableType,Example1.table.Cols) do not conform to the expected kinds of the type parameters (type F,type A,type B).
[error] Example1.table.Repr[X]'s type parameters do not match type F's expected parameters:
[error] type Repr has one type parameter, but type F has one
[error]   val deleted = deleteFrom(table).where(age === 3)
[error]                 ^
[error] /home/circleci/project/examples/src/main/scala/Example1.scala:39:28: type mismatch;
[error]  found   : Example1.Table.Source{type Repr[X] = Example1.columnSet.ColumnsRepr[X]; type Cols = Int :*: Example1.ColumnSet.Singleton[String]}
[error]     (which expands to)  Example1.Table.Source{type Repr[X] = (Example1.Expr[Example1.Features.Source,X,Int], (Example1.Expr[Example1.Features.Source,X,String], Unit)); type Cols = Example1.ColumnSet.Cons[Int,Example1.ColumnSet.Cons[String,Example1.ColumnSet.Empty.type]]}
[error]  required: Example1.Table.Source.Aux[F,A,B]
[error]     (which expands to)  Example1.Table.Source{type Repr[X] = F[X]; type TableType = A; type Cols = B}
[error]   val deleted = deleteFrom(table).where(age === 3)
```

**Comment by jdegoes** [comment]
All right, let's take a look tomorrow if you can.

**Comment by jczuchnowski** [comment]
@jdegoes I will comment out the failing examples and create a ticket for fixing it. This PR is already useful to push forward the work for the hackathon.

**Pull request merged**
