### PR TITLE
Add sbt-tpolecat and move examples to sub-project

### PR DESCRIPTION
**Pull request by lemastero**
Changes:
* move Examples into separate sub-project - similar approach is in zio, zio-nio,
* scalafmtAll
* add plugin `sbt-tpolecat` as in `zio-nio`

### CODE REVIEW

**Comment by softinio** [comment]
@lemastero @mijicd Most projects aren't using `sbt-tpolecat` I am fine with it, but if we want to start standardizing on it more widely shall we add it to our seed?

**Comment by mijicd** [comment]
@softinio agreed.

**Comment by lemastero** [comment]
Closing this guy. I wanted to improve this project using some principles I try to follow when writing code:
* turn on all static code analysis from the compiler (via sbt-topolecat plugin)
* put code in proper packages
* separate real code from samples

But maybe I am too opinionated :)

**Comment by mijicd** [comment]
@lemastero these makes perfect sense actually. What @softinio pointed above is that it would be nice to have them in our library giter8 template, so that the other projects are started with proper setup :).

**Pull request closed without merging**
