### PR TITLE
Add missing aggregation functions

### PR DESCRIPTION
**Pull request by marekklis**
For #6 

@jdegoes is it enough?

### CODE REVIEW

**Comment by jdegoes** [comment]
@marekklis Fantastic start!

I'd look [here](https://www.oreilly.com/library/view/sql-in-a/9780596155322/ch04s02.html) and add any that are supported on all the latest versions of: MySQL, Postgres, SQL Server, and Oracle.

**Comment by jczuchnowski** [comment]
I see later specs (2011) define also 
- STDDEV_POP
- STDDEV_SAMP
- VAR_SAMP
- VAR_POP
And both PostgreSQL and MS SQL support some form of it. I guess we could add these if MySQL and Oracle also support them.

**Comment by marekklis** [comment]
I thought that this issue is about adding aggregate functions defined by ANSI-92 standard. Based on [this](https://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt) doc these functions are: `count`, `sum`, `avg`, `min`, `max`. 
@jdegoes @jczuchnowski I'll add more functions you suggested

**Comment by jdegoes** [comment]
I think ANSI-92 should be the guide, but if some function is supported by all 4 databases, then it's safe for inclusion, even if it does _not_ appear in any ANSI standard. Meanwhile, if something appears even in ANSI-92, but it is not supported by one of the 4, it should not appear in the `Sql` module.

**Comment by marekklis** [comment]
Based on the following docs:

- https://dev.mysql.com/doc/refman/8.0/en/group-by-functions.html
- https://www.postgresql.org/docs/current/functions-aggregate.html
- https://docs.microsoft.com/en-us/sql/t-sql/functions/aggregate-functions-transact-sql?view=sql-server-ver15
- https://docs.oracle.com/database/121/SQLRF/functions003.htm#SQLRF20035
aggregation functions supported by all 4 servers (mysql, postgresql, sql sever and oracle) are:

1. `AVG()`	     
2. `COUNT()`      
3. `MAX()`	     
4. `MIN()`	     
5. `SUM()`
6. `STDDEV()`	 (`STDEV` for SQL Server)
7. `STDDEV_POP()` (`STDEVP` for SQL Server)
8. `STDDEV_SAMP()` (`STDEV` for SQL Server)	     
9. `VAR_POP()`	 (`VARP` for SQL Server)
10. `VAR_SAMP()`   (`VAR` for SQL Server)
11. `VARIANCE()`	 (`VARP` for SQL Server)

**Comment by marekklis** [comment]
@jdegoes Should I add `STDDEV_POP`, `STDDEV_SAMP`, `VAR_POP` and `VAR_SAMP` functions (even if the name of these functions are a bit different for SQL Server)?

**Comment by jdegoes** [comment]
If the names are different, we should not include them here, but rather we can add them later in subtypes of `Sql`, e.g. `SqlServer extends Sql`, etc.

**Pull request merged**
