### PR TITLE
new insert module

### PR DESCRIPTION
**Pull request by jotarada**
to solve #55

### CODE REVIEW

**Comment by jczuchnowski** [comment]
We'll have to work on it some more. `SelectionSet` is problematic here after all. It allows to do weird things like `val colsToInsert = age ++ Ascii(name)`.
Also `.values` should take the whole row of values to insert. Otherwise it'll be possible to construct a bad guery.

**Comment by jotarada** [comment]
I think i need help on this.

can `SelectionSet` be replaced with `Selection` ? 

values should be be warped inside a List? the problem will persist because the list can not have all the fields.

**Comment by jczuchnowski** [comment]
@jotarada let me get back to you on that. It's pretty important we get it right.

**Comment by robmwalsh** [comment]
@jotarada I think we should be able use ColumnSet (or we'll have to create something similar) - this would allow us to keep track of the types (and, importantly, the order) of each column specified, ensure that the columns all came from the table specified, and allow us to enforce the types line up in values, so the `values` function could take a vararg of `ValueSet`s (which will need to be created) to have our DSL behave something like. note that the ++ operator in the set of values wouldn't be the same as on ColumnSet
```scala
//should work
insertInto(customers){fName ++ lName ++ dob} values ("Joe" ++ "Bloggs" ++ LocalDate.of(1990, 1, 8), "Matt" ++ "Smith" ++ LocalDate.of(1978, 4, 5))
//shouldn"t work (not enough arguments)
insertInto(customers ){fName ++ lName ++ dob} values ("Joe" ++ "Bloggs", "Matt" ++ "Smith")
//shouldn"t work (order of types doesn"t align)
insertInto(customers ){fName ++ lName ++ dob} values ("Joe" ++ LocalDate.of(1990, 1, 8) ++ "Bloggs", "Matt" ++ LocalDate.of(1990, 1, 8) ++ "Smith")
```
happy to pair with you on this if you'd like

**Comment by jczuchnowski** [comment]
Closing this. In the end it was implemented here https://github.com/zio/zio-sql/pull/550

**Pull request closed without merging**
